{
    "value0": {
        "value0": [
            "barrel",
            "Main Camera",
            "Directional Light"
        ],
        "value1": {
            "value0": [
                "child 1",
                "child 2"
            ],
            "value1": {
                "value0": [],
                "value1": {
                    "value0": {
                        "value0": 0.0,
                        "value1": 0.0,
                        "value2": 0.0
                    },
                    "value1": {
                        "value0": 1.0,
                        "value1": 0.0,
                        "value2": 0.0,
                        "value3": 0.0
                    },
                    "value2": {
                        "value0": 0.0,
                        "value1": 0.0,
                        "value2": 0.0
                    },
                    "value3": {
                        "value0": 0.0,
                        "value1": 0.0,
                        "value2": 0.0
                    },
                    "value4": {
                        "value0": 0.0,
                        "value1": 0.0,
                        "value2": 0.0
                    },
                    "value5": {
                        "value0": 1.0,
                        "value1": 0.0,
                        "value2": 0.0,
                        "value3": 0.0
                    },
                    "value6": {
                        "value0": 1.0,
                        "value1": 1.0,
                        "value2": 1.0
                    }
                },
                "value2": []
            },
            "value2": {
                "value0": [],
                "value1": {
                    "value0": {
                        "value0": 0.0,
                        "value1": 0.0,
                        "value2": 0.0
                    },
                    "value1": {
                        "value0": 1.0,
                        "value1": 0.0,
                        "value2": 0.0,
                        "value3": 0.0
                    },
                    "value2": {
                        "value0": 0.0,
                        "value1": 0.0,
                        "value2": 0.0
                    },
                    "value3": {
                        "value0": 0.0,
                        "value1": 0.0,
                        "value2": 0.0
                    },
                    "value4": {
                        "value0": 0.0,
                        "value1": 0.0,
                        "value2": 0.0
                    },
                    "value5": {
                        "value0": 1.0,
                        "value1": 0.0,
                        "value2": 0.0,
                        "value3": 0.0
                    },
                    "value6": {
                        "value0": 1.0,
                        "value1": 1.0,
                        "value2": 1.0
                    }
                },
                "value2": []
            },
            "value3": {
                "value0": {
                    "value0": 0.0,
                    "value1": 0.0,
                    "value2": 0.0
                },
                "value1": {
                    "value0": 1.0,
                    "value1": 0.0,
                    "value2": 0.0,
                    "value3": 0.0
                },
                "value2": {
                    "value0": 0.0,
                    "value1": 0.0,
                    "value2": 0.0
                },
                "value3": {
                    "value0": 0.0,
                    "value1": 0.0,
                    "value2": 0.0
                },
                "value4": {
                    "value0": 0.0,
                    "value1": 0.0,
                    "value2": 0.0
                },
                "value5": {
                    "value0": 1.0,
                    "value1": 0.0,
                    "value2": 0.0,
                    "value3": 0.0
                },
                "value6": {
                    "value0": 1.0,
                    "value1": 1.0,
                    "value2": 1.0
                }
            },
            "value4": [
                1,
                4,
                6
            ],
            "value5": {
                "value0": "../../LobsterGameEngine/res/meshes/Barrel_01.obj",
                "value1": [
                    "materials/barrel.mat"
                ]
            },
            "value6": {}
        },
        "value2": {
            "value0": [],
            "value1": {
                "value0": {
                    "value0": 0.0,
                    "value1": 2.0,
                    "value2": 10.0
                },
                "value1": {
                    "value0": 1.0,
                    "value1": 0.0,
                    "value2": 0.0,
                    "value3": 0.0
                },
                "value2": {
                    "value0": 0.0,
                    "value1": 0.0,
                    "value2": 0.0
                },
                "value3": {
                    "value0": 0.0,
                    "value1": 0.0,
                    "value2": 0.0
                },
                "value4": {
                    "value0": 0.0,
                    "value1": 0.0,
                    "value2": 0.0
                },
                "value5": {
                    "value0": 1.0,
                    "value1": 0.0,
                    "value2": 0.0,
                    "value3": 0.0
                },
                "value6": {
                    "value0": 1.0,
                    "value1": 1.0,
                    "value2": 1.0
                }
            },
            "value2": [
                2,
                4,
                7
            ],
            "value3": {
                "value0": 45.0,
                "value1": 0.10000000149011612,
                "value2": 100.0
            },
            "value4": {}
        },
        "value3": {
            "value0": [],
            "value1": {
                "value0": {
                    "value0": 0.0,
                    "value1": 2.0,
                    "value2": 3.0
                },
                "value1": {
                    "value0": 1.0,
                    "value1": 0.0,
                    "value2": 0.0,
                    "value3": 0.0
                },
                "value2": {
                    "value0": 0.0,
                    "value1": 0.0,
                    "value2": 0.0
                },
                "value3": {
                    "value0": 0.0,
                    "value1": 0.0,
                    "value2": 0.0
                },
                "value4": {
                    "value0": 0.0,
                    "value1": 0.0,
                    "value2": 0.0
                },
                "value5": {
                    "value0": 1.0,
                    "value1": 0.0,
                    "value2": 0.0,
                    "value3": 0.0
                },
                "value6": {
                    "value0": 1.0,
                    "value1": 1.0,
                    "value2": 1.0
                }
            },
            "value2": [
                3,
                4
            ],
            "value3": {
                "value0": 0,
                "value1": {
                    "value0": 1.0,
                    "value1": 1.0,
                    "value2": 1.0
                }
            },
            "value4": {}
        }
    }
}