{
    "value0": {
        "value0": [
            "barrel",
            "Main Camera",
            "Directional Light"
        ],
        "value1": {
            "value0": [
                "child 1",
                "child 2"
            ],
            "value1": {
                "value0": [],
                "value1": []
            },
            "value2": {
                "value0": [],
                "value1": []
            },
            "value3": [
                "N7Lobster13MeshComponentE",
                "N7Lobster9RigidbodyE"
            ],
            "value4": {
                "value0": "../../LobsterGameEngine/res/meshes/Barrel_01.obj",
                "value1": [
                    "materials/barrel.mat"
                ]
            }
        },
        "value2": {
            "value0": [],
            "value1": [
                "N7Lobster15CameraComponentE",
                "N7Lobster9RigidbodyE"
            ],
            "value2": {
                "value0": 45.0,
                "value1": 0.10000000149011612,
                "value2": 100.0
            }
        },
        "value3": {
            "value0": [],
            "value1": [
                "N7Lobster14LightComponentE",
                "N7Lobster9RigidbodyE"
            ],
            "value2": {
                "value0": 0,
                "value1": {
                    "value0": 1.0,
                    "value1": 1.0,
                    "value2": 1.0
                }
            }
        }
    }
}